version: "2.3"
#this file is intended to be used as quick service setup on any x86 machine
services:
    postgres:
        container_name: service-postgres
        image: nfrmtk/ratings-postgres:latest
        environment:
          - POSTGRES_DB=ratings_service_db-1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - "5432"
        networks:
          - main

    ratings_service-container:
        image: nfrmtk/ratings:latest
        privileged: true
        restart: always
        environment:
          - POSTGRES_DB=ratings_service_db-1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
        ports:
          - "8080:8080"
        depends_on:
          - postgres
        networks:
          - main

    proxy:
      image: nginx:latest
      ports:
        - "8000:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      links:
        - ratings_service-container
      networks:
        - main
networks:
    main:
        driver: bridge
